name: proj
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  flutter_hooks: ^0.20.0
  intl:
    path: ./local_packages/intl/intl-master
  cached_network_image: ^3.3.0
  go_router: ^14.0.0
  get_it: ^7.6.0
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.2

  dio: ^5.0.0
  retrofit: ^4.0.1

  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  dartssh2: ^2.13.0
  xterm: ^4.0.0
  postgres: ^3.5.8
  web_socket_channel: ^3.0.3
  http: ^1.2.0

  build_runner: ^2.4.6
  retrofit_generator: ^10.2.0
  json_serializable: ^6.7.1

dependency_overrides:
  analyzer: ^8.3.0

flutter:
  uses-material-design: true
